### ISSUE TITLE
Fix setup bugs

### ISSUE THREAD

**Issue by raamana** [Open-Minds-Lab/openminds#1]
There is some issues with basic local setup and installation, so I would work off GitHub. I am not sure why this isn't compiling here.

Hi @anibalsolon, are you familiar with this setup? Can you help me? if not, I will dump this and find another template :)

**Comment by raamana** [comment]
I went through docs: but installing Ruby etc seems to be a pain on my mac.. I can walk you through this structure so you can help debug this stuff if your time permits. I'd understand if you are busy.

**Comment by anibalsolon** [comment]
hey @raamana I managed to build it locally- could it be a wrong setup on Github Pages?

![image](https://user-images.githubusercontent.com/562525/140957645-07299e1b-0bef-4a15-acff-902ce8b2e43c.png)

**Comment by anibalsolon** [comment]
these are the commands I've used on Ubuntu to setup everything (didnt even had ruby-dev installed)
```
sudo apt-get install ruby-dev
sudo gem install bundler
sudo bundler
bundle exec jekyll serve
```

**Comment by raamana** [comment]
yeah, glad to see it worked on your machine! Yes, there is an issue on github pages or a setup of this repo w.r.t getting it out on the web.. are you familiar with this template, to try identify the issue? thanks,

**Comment by raamana** [comment]
so there is something at https://open-minds-lab.github.io/openminds/

but the layout is all messed up etc :)

**Comment by anibalsolon** [comment]
Ah I see now- I was checking this URL https://openmindslab.github.io/

So you just need to set the URL to the correct one at:
https://github.com/Open-Minds-Lab/openminds/blob/master/_config.yml#L14

i.e.
```yaml
url: "https://open-minds-lab.github.io/openminds/"
```

**Comment by raamana** [comment]
I [changed it](https://github.com/Open-Minds-Lab/openminds/runs/4169595269) but the layout isn't changed for some reason

**Comment by anibalsolon** [comment]
@raamana the org name contains hyphens, so it should be `open-minds-lab`

**Comment by raamana** [comment]
damn, how did I miss that! that did it! thanks..

its kinda weird to have to hyphens in the URL though.. will try to see how to remove that (and I forgot why the repo name has hyphens in the first place)

**Comment by raamana** [comment]
thanks for the help mate, it worked.
